travis:
  secure:
    BINSTAR_TOKEN: kLNuTz4qGebSVxcdWMNf58UVk82Sb/0znUHMmWOZd4LYKtR0ShBjQLyJrc9IdW6G+WjVaU6iZ7tUiIGR2iXBsK9vyMrz2upf4+MXwfnWXp/XSb8U2uRIiXjSsJOAO3XEmwckvfNfyNistR7fCPGwinM1wyaCZ7q/5z1xYDVomGoZnkQARndqtO3wskJF+a5PPa0+aDgfV7oUl220715wqom/u6dAX3aDUI03P8LoARXgg9AXmWaz6NxEDh/I7zTbpWWke+DWchGyP4RxlfXcEBxx1apnprX7LVqieEpk5oyAd2SPGd6gB2wSfCHGmKfRZq2n1cevmp+RaONLfmTwN+uqcSTEzlhv8GC4RbMVlB6AjZT1CIzPbGuL338mwRzS/RX2CuwaOUSSXfkqEl3VKspjZQ1HHMkSntMhH6OUOMUr9oei3+/WpmSitYSyVc5EXOMBx4X3Rnl6tUnuzrKYTxqfq1dUegfTWGmd1r9330voMvxDFxmNEFIk7A3RQhA+Y86efUYY5wm40aWY3i5hjGtS1XmcjquNMwgPG943XMv0HXdxKP1Z9t9IRd8WMQ9xBjjdCqZzqAdDVa/VMtNuhUpbc9Eu7QqrhKxcyJuLeAodoo8cJyw4GOyNb6/wLxLCVAUsTfaY1dC4yUmfFhgwgduMEwuFkDN9FBalm3Nr640=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
